### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by vortechs2000** [steeve/python-lz4#11]
There's currently no license (or copyright) mentioned in the python-lz4 code.  Is there one that you're thinking of for the python wrapper code?

**Comment by steeve** [comment]
Didn't think of it, but it seems good to me to use lz4's one, New BSD: http://opensource.org/licenses/BSD-3-Clause

**Comment by vortechs2000** [comment]
Would you be open to a pull request adding the copyright info to the top of the python specific source files?

**Comment by steeve** [comment]
Sure throw ahead

**Comment by vortechs2000** [comment]
Would you be ok with the 2-clause form? This is what's in the lz4 code proper:  http://opensource.org/licenses/BSD-2-Clause

The 3 clause references an ORGANIZATION in the 3rd clause, and I don't know what would go there...and if I modify it to not have the ORGANIZATION part of clause 3, is it still valid?

**Comment by jd-boyd** [comment]
Is this resolved and ready to be closed?
