### ISSUE TITLE
Change compression level

### ISSUE THREAD

**Issue by josephernest** [steeve/python-lz4#17]
Here we see that different compressions levels are available : http://fastcompression.blogspot.fr/p/lz4.html :

```
Compression levels of 0 to 2 translates into "fast compression" (default).
Compression levels of 3 to 9 translates into "High compression".
```

How to change compression level with

```
lz4.dumps(...)
```

?

**Comment by steeve** [comment]
You need to use `lz4.compressHC`

**Comment by josephernest** [comment]
Thanks @steeve ! Closing this.
