### ISSUE TITLE
__version__ support?

### ISSUE THREAD

**Issue by apiszcz** [steeve/python-lz4#19]
Implement the python **version** variable support.

(Pdb) dir(lz4)
['LZ4_compress', 'LZ4_uncompress', '**doc**', '**file**', '**name**', '**package**', 'compress', 'compressHC', 'decompress', 'dumps', 'loads', 'uncompress']

**Comment by totaam** [comment]
+1
rationale: it would be nice to be able to tell when the version installed on the user's machine is broken (or vulnerable) so we can give them a nudge (or in our case, switch to another compressor if needed)

Thanks
