### ISSUE TITLE
Not portable across different platforms

### ISSUE THREAD

**Issue by chimatix** [steeve/python-lz4#2]
Because the compressed length is stored as an int, the binding can't be used in a heterogeneous environment, with architectures of different endianness and size. This should probably be handled internally by lz4 like the Snappy libary does. As it is, I'm probably going to have to report the same bug in a different language binding when we use a component in a different language.

**Comment by steeve** [comment]
You are completely right. However, LZ4 doesn't define a container format (yet?).
About endianess. we could define it right away and add some conversion code if on big endian machines.

About the int, I'll switch it to uint32_t defined in stdint.h. This should take care of int size.

**Comment by Cyan4973** [comment]
This is correct, this should be handled by LZ4.
I'll get a proposition ready for container format soon.

**Comment by gray** [comment]
This is what I just implemented for the Perl interface: gray/compress-lz4@243e803cbd4fb0a6fd0ad9dacfed9df0260bb0fe

It should handle both the integer size and endian issues.

**Comment by steeve** [comment]
@gray: Sorry for asking but how will it solve endianness at decode time? Shouldn't you branch depending on endianness instead ?

UPDATE: just read Rob Pike's post, indeed, I'll update this when I have some time :)

**Comment by Cyan4973** [comment]
A discussion is starting on http://fastcompression.blogspot.fr/
in order to define a framing format for LZ4.
Comments and contributions are welcomed.

**Comment by steeve** [comment]
Oh nice, thanks for the heads up!

**Comment by bos** [comment]
I just submitted gh-4, which along with fixing a bunch of serious bugs, defines a header format that is (a) good enough for now (b) portable and (c) compatible with the current de facto header on most architectures - it's a 32-bit little endian length.

**Comment by steeve** [comment]
0.4.0 published on PyPI: http://pypi.python.org/pypi/lz4
