### ISSUE TITLE
new alias for uncompress -> decompress

### ISSUE THREAD

**Issue by mpaladin** [steeve/python-lz4#3]
Hello,

looking at compatibility with other modules, what do you think about adding a "decompress" alias?
So it could be:
lz4.LZ4_uncompress == lz4.uncompress == lz4.loads == lz4.decompress

This would allow compatibility with zlib which doesn't have an uncompress method.
snappy has both uncompress and decompress.

Cheers,
-Massimo

**Comment by steeve** [comment]
You're right, the goal is to be as compatible as possible.
I'll add it tonight (europe)!

**Comment by mpaladin** [comment]
great, thanks!
