### ISSUE TITLE
Active Fork

### ISSUE THREAD

**Issue by mrocklin** [steeve/python-lz4#51]
I find this library useful.  Unfortunately it does not appear to be maintained.

@steeve are you actively maintaining this library?  Would you be willing to grant others commit rights to this repository and maintenance/ownership rights to the PyPI name?

Alternatively, maybe we should consider an active fork.  @jonathanunderwood where do you keep the fork used by Fedora?

**Comment by jonathanunderwood** [comment]
My fork is here:

https://github.com/jonathanunderwood/python-lz4

I had been thinking the same thing, and would be willing to maintain such a fork. I'll try and contact @Steeve on twitter as I see he's active there.

**Comment by jonathanunderwood** [comment]
There's also this fork which ports to the cffi:

https://github.com/GregBowyer/lz4-cffi/

**Comment by steeve** [comment]
hey folks, indeed I don't have time to maintain it

i'll be happy to add people as contributors to the project though

**Comment by jonathanunderwood** [comment]
Thanks for replying @steeve. PyPi seems to be broken currently, but once it's working properly I'll register a username there and hopefully you can add me to the project there.

In the meantime, I've merged @mrocklin and my own changes into the master branch of my repo, and hopefully we can make a 0.8.0 release from that.

**Comment by mrocklin** [comment]
I'm not sure I qualify as a full collaborator (I haven't contributed nearly as much as @jonathanunderwood ) however, if you would like to add my accounts for maintenance reasons I'm @mrocklin both on github and PyPI.

**Comment by jonathanunderwood** [comment]
Great to have you on board @mrocklin !

**Comment by jonathanunderwood** [comment]
I've also now merged changes from @keeely to build on VS 2008. But I have no way of testing those, sadly.

**Comment by keeely** [comment]
pkg-config (setup.py) isn't there for Windows, but once I'd fixed that got a truck load of other warnings, __GNUC stuff needs to be #ifdef'ed out for win32.  I'm not using this any more, so can't really justify the time to fix it, but perhaps I'll come back to it later.  Thanks.

**Comment by jonathanunderwood** [comment]
OK, I am now registered on PyPi, username jgu - it'd be great if @steeve could add me as a maintainer to the package on there.

**Comment by mrocklin** [comment]
Ping @steeve .  Would you be willing to log into http://pypi.python.org and provide `jgu` with ownership rights over the lz4 package?

**Comment by steeve** [comment]
there you go folks, i've added @mrocklin as maintaner here, and @jonathanunderwood as maintainer on pypi

**Comment by mrocklin** [comment]
Thank you @steeve !

@jonathanunderwood do you have a stable/tested version of `python-lz4` with the recent changes that can be pushed up to PyPI in the near future?

**Comment by steeve** [comment]
my bad, i've added @jonathanunderwood as maintainer here (guess it makes more sense ?)

**Comment by mrocklin** [comment]
The main thing is that someone else has push access to PyPI.  We can always devolve to decentralized git if necessary (indeed, I think that @jonathanunderwood has been operating this way for a while now.)

**Comment by jonathanunderwood** [comment]
Thanks @steeve !

@mrocklin I have my own cloned/forked repo that is essentially what I've been pushing to the Fedora packages. What I propose to do is create a github organization called python-lz4 and create a repo under that also called python-lz4. To that organization I'll add all folks interesting in contributing. And I'll make a pypi release off it. But, it's time for bed here, so it'll happen tomorrow :)

**Comment by mrocklin** [comment]
Sounds like a good plan.  Thanks for taking the lead on this.

On Tue, Apr 26, 2016 at 4:47 PM, jonathanunderwood <notifications@github.com

**Comment by jonathanunderwood** [comment]
OK, I've finished the lift of the git repo and created an organization:

https://github.com/python-lz4

This is @steeve's repo with all of my commits on top.

I've sent invites to @mrocklin and @steeve to be owners. If you're uncomfortable being an owner and would prefer instead to be a member, you can reject the invite, and I'll send another inviting you to be a member.

**Comment by jonathanunderwood** [comment]
OK, and I've successfully cut a new release on pypi, 0.8.1. So, we're up and running.
