### ISSUE TITLE
Importing from lz4

### ISSUE THREAD

**Issue by frmdstryr** [steeve/python-lz4#52]
Is it possible to import from tar.lz4 like the standard zipimporter? If not, how difficult would it be to add this?

Thanks!

**Comment by jonathanunderwood** [comment]
This project is now maintained here: https://github.com/python-lz4/python-lz4. So, you should probably raise this issue there. However, you'll need to provide a bit more detail :)

**Comment by frmdstryr** [comment]
Ok will recreate it there
